baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "https://gm.origem.net.br" # the base hostname & protocol for your site

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "vendor"
  - "send.sh"
